#!/usr/bin/env python3
"""
Generate secure secrets for production deployment.

Run this once and save all the output values safely.
You'll need these for Render, Supabase, and Upstash setup.
"""

import secrets
from cryptography.fernet import Fernet


def generate_secrets():
    """Generate all required secrets for production."""

    print("=" * 70)
    print("SECURE SECRETS GENERATOR")
    print("=" * 70)
    print("\nGenerating production-grade secrets...\n")

    # Generate SECRET_KEY for Flask
    secret_key = secrets.token_urlsafe(32)
    print("SECRET_KEY (Flask session signing):")
    print(f"  {secret_key}")
    print()

    # Generate API_ACCESS_KEY for machine authentication
    api_key = secrets.token_urlsafe(32)
    print("API_ACCESS_KEY (Machine authentication):")
    print(f"  {api_key}")
    print()

    # Generate ENCRYPTION_KEY for Fernet (token encryption)
    encryption_key = Fernet.generate_key().decode()
    print("ENCRYPTION_KEY (Fernet encryption):")
    print(f"  {encryption_key}")
    print()

    # Show example .env.production section
    print("=" * 70)
    print("COPY-PASTE into Render Environment Variables:")
    print("=" * 70)
    print()
    print(f"SECRET_KEY={secret_key}")
    print(f"API_ACCESS_KEY={api_key}")
    print(f"ENCRYPTION_KEY={encryption_key}")
    print()
    print("# Then add these from your accounts:")
    print("DATABASE_URL=postgresql://user:pass@host:5432/postpilot  # From Supabase")
    print("REDIS_URL=redis://:password@host:port  # From Upstash")
    print("CLERK_SECRET_KEY=sk_test_...  # From Clerk Dashboard")
    print("LINKEDIN_CLIENT_ID=...  # From LinkedIn Developer Portal")
    print("LINKEDIN_CLIENT_SECRET=...  # From LinkedIn Developer Portal")
    print("NVIDIA_API_KEY=nvapi-...  # From NVIDIA NIM Dashboard")
    print("CORS_ORIGINS=https://postpilot.vercel.app")
    print("FLASK_ENV=production")
    print("SCHEDULER_ENABLED=true")
    print()

    # Save to .env.production.local - a real secrets file, gitignored, named
    # so it can never be mistaken for a safe-to-commit template. The values
    # above are live and usable as-is; a file called "*.example" must never
    # contain them, since that name signals "placeholder, safe to share."
    real_env = f"""# Production Environment Variables
# Generated by generate_secrets.py - contains REAL secrets, do not commit

# ============ SECRETS (Generated - Keep Secure!) ============
SECRET_KEY={secret_key}
API_ACCESS_KEY={api_key}
ENCRYPTION_KEY={encryption_key}

# ============ DATABASE (From Supabase) ============
DATABASE_URL=postgresql://user:password@host.supabase.co:5432/postgres
REDIS_URL=redis://:password@host.upstash.io:port

# ============ AUTHENTICATION ============
CLERK_SECRET_KEY=sk_test_...

# ============ LINKEDIN OAUTH ============
LINKEDIN_CLIENT_ID=your_id_here
LINKEDIN_CLIENT_SECRET=your_secret_here

# ============ AI/ML ============
NVIDIA_API_KEY=nvapi-...

# ============ FLASK ============
FLASK_ENV=production
FLASK_PORT=5000
DEBUG=false

# ============ API ============
CORS_ORIGINS=https://postpilot.vercel.app
SCHEDULER_ENABLED=true
LOG_LEVEL=INFO
"""

    with open('.env.production.local', 'w') as f:
        f.write(real_env)

    print("✅ Saved to: .env.production.local (gitignored - contains real secrets)")
    print()
    print("=" * 70)
    print("NEXT STEPS:")
    print("=" * 70)
    print("1. Save the three generated secrets above to a secure location")
    print("2. Create accounts on: Supabase, Upstash, Render")
    print("3. Get your keys from: Clerk, LinkedIn, NVIDIA")
    print("4. Add all values to Render Environment Variables")
    print("5. Deploy!")
    print()


if __name__ == "__main__":
    generate_secrets()
